name: MyBed
main: com.codisimus.plugins.mybed.MyBed
version: 0.7.1
author: Codisimus
website: www.codisimus.com
description: Players cannot sleep in other Players' beds
startup: postworld
depend: [Vault]
permissions:
  mybed.own:
    default: true
    description: Needed to own a bed
  mybed.inn:
    default: op
    description: Needed to create an Inn
  mybed.server_inn:
    default: op
    description: Needed to create a Server Inn
  mybed.guest:
    default: true
    description: Needed to create a Guest Bed
  mybed.admin:
    default: op
    description: Allows you to destroy another Player's Bed